export { default as Title } from './Title'
export { default as Logo } from './Logo'
export { default as Search } from './Search'
export { default as Header } from './Header'
export { default as Content } from './Content'
export { default as Footer } from './Footer'
